In [56]:
import numpy as np

In [57]:
a = np.array([[25, 10]])
b = np.array([[12, 50]])

print(a)
print(b)


[[25 10]]
[[12 50]]


In [58]:
(a+b).T # T = transpose

array([[37],
       [60]])

In [59]:
x = 3
a = np.array([[21, 12]])

(a*x).T

array([[63],
       [36]])

In [60]:
np.dot(a, x) #

array([[63, 36]])

In [61]:
# perkalian 2 vektor 1D
a = np.array([2, 3, 3])
b = np.array([4, 5,3])
hasil = np.dot(a, b)
print("perhitungan manual")
print(2*4 + 3*5 + 3*3)
print(10*"=")
print("perhitungan dengan fungsi dot di numpy")
print(hasil)

perhitungan manual
32
perhitungan dengan fungsi dot di numpy
32


In [62]:
# perkalian vektor 1D dengan matriks 2D
a = np.array([10, 20])
b = np.array([[15, 29], [2, 3]])
hasil = np.dot(a, b)
print(hasil)

[190 350]


In [63]:
x = np.array([[10, 21], [12, 4]])
y = np.array([[2, 5], [8, 4]])
hasil = np.dot(x, y)
print(hasil, end= " = x and y\n\n")

[[188 134]
 [ 56  76]] = x and y



In [64]:
# penjumlahan matriks
x = np.array([[20, 88], [76, 12], [12, 4]])
y = np.array([[2, 8], [3, 2], [4, 8]])

print(x, end= " = x \n\n")
print(y, end= " = y \n\n")

print(x + y)
print()
print(x - y)

[[20 88]
 [76 12]
 [12  4]] = x 

[[2 8]
 [3 2]
 [4 8]] = y 

[[22 96]
 [79 14]
 [16 12]]

[[18 80]
 [73 10]
 [ 8 -4]]


In [65]:
x = np.array([[20, 2], [54, 4], [12, 92]])
y = np.array([[2, 8], [2, 5], [4, 8]])
z = 3
w = 2
print(x, end= " = x\n\n")
print(y, end= " = y\n\n")

x - y


[[20  2]
 [54  4]
 [12 92]] = x

[[2 8]
 [2 5]
 [4 8]] = y



array([[18, -6],
       [52, -1],
       [ 8, 84]])

In [66]:
x * z

array([[ 60,   6],
       [162,  12],
       [ 36, 276]])

In [71]:
x /w 

array([[10.,  1.],
       [27.,  2.],
       [ 6., 46.]])

In [72]:
a = np.eye(4) # parameter ini menunjukkan ukuran dimensi
print(a, end= " = a\n\n")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] = a



In [74]:
b = np.eye(2, 4)
print(b, end= " = b\n\n")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]] = b



In [80]:
c = np.eye(2, 5 , order="F")
print(c, end= " = c\n\n")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]] = c



In [84]:
x = np.array([[1, 2], [3, 4]])
x_invers = np.linalg.inv(x) # inv / invers adalah kebalikan dari sesuatu/lawan nya
print(x, end= " = x\n\n")
print(x_invers, end= " = x_invers")

[[1 2]
 [3 4]] = x

[[-2.   1. ]
 [ 1.5 -0.5]] = x_invers

In [86]:
x_det = np.linalg.det(x)
print(x, end= " = x\n\n")
print(x_det, end= " = x_det")

[[1 2]
 [3 4]] = x

-2.0000000000000004 = x_det

In [92]:
a = np.array([ [[2, 3], [4, 5]], 
               [[4, 7], [2, 5]] 
              ])
print(np.linalg.det(a))


[-2.  6.]
